services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bd2024
      POSTGRES_DB: BaseDatos
    ports:
      - "5433:5433"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clients:
        build:
          context: .
          dockerfile: ./Dockerfile-client
        ports:
          - "8080:8080"

  account:
      build:
        context: .
        dockerfile: ./Dockerfile-account
      ports:
        - "8081:8081"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: